"""Mordred setup API: a shim; the code ships in the hermes-mordred package.

This file lives in ``<home>/plugins/mordred/dashboard/``, outside Hermes's
Python environment, so it still loads after a Hermes update rebuilt that
environment without Mordred. Then it serves a small fallback API (stdlib +
FastAPI, which Hermes's dashboard server always has) so the Mordred page can
say what happened and repair it: ``hermes pm install venv`` rebuilds the
environment from its inputs, which include ``../pyproject.toml`` (Mordred's
package-manager member) when Mordred registered one.
"""

from __future__ import annotations

try:
    from mordred_hermes.desktop.api import router
except ImportError as _missing:  # Mordred is not in this environment
    import os
    import subprocess
    import sys
    import threading
    import tomllib
    from pathlib import Path
    from typing import Any

    from fastapi import APIRouter

    router = APIRouter()
    _REASON = f"{type(_missing).__name__}: {_missing}"
    _MEMBER = Path(__file__).resolve().parent.parent
    _REPAIR: dict[str, Any] = {"state": "idle", "code": None, "output": ""}
    _LOCK = threading.Lock()

    def _member() -> dict[str, Any]:
        target = _MEMBER / "pyproject.toml"
        if not target.is_file():
            return {"present": False}
        try:
            text = target.read_text(encoding="utf-8")
            data = tomllib.loads(text)
        except (OSError, ValueError):
            return {"present": True, "valid": False}
        recorded = data.get("tool", {}).get("hermes-mordred", {})
        return {
            "present": True,
            "valid": "GENERATED by hermes-mordred" in text and (_MEMBER / "mordred_hermes").is_dir(),
            "version": data.get("project", {}).get("version"),
            "source": recorded.get("source"),
            "path": recorded.get("path") or None,
            "extras": list(recorded.get("extras") or []),
        }

    def _environment() -> dict[str, Any]:
        prefix = Path(sys.prefix)
        env_id = prefix.parent.name if prefix.name == "venv" else prefix.name
        return {"prefix": str(prefix), "environment": env_id, "python": sys.version.split()[0]}

    def _repair_view() -> dict[str, Any]:
        with _LOCK:
            return dict(_REPAIR)

    @router.get("/status")
    async def status() -> dict[str, Any]:
        return {
            "ok": False,
            "error": "mordred_not_installed",
            "installed": False,
            "reason": _REASON,
            "environment": _environment(),
            "member": _member(),
            "repair": _repair_view(),
        }

    @router.get("/health")
    async def health() -> dict[str, Any]:
        return await status()

    def _run_repair() -> None:
        # The supported rebuild: pm syncs the selected environment with every
        # enabled plugin member, then selects it. This process keeps the old
        # environment until Hermes restarts.
        command = [sys.executable, "-m", "hermes_cli.main", "pm", "install", "venv"]
        try:
            result = subprocess.run(
                command,
                capture_output=True,
                text=True,
                timeout=1800,
                env=dict(os.environ),
                stdin=subprocess.DEVNULL,
                check=False,
            )
            output, code = (result.stdout or "") + (result.stderr or ""), result.returncode
        except (OSError, subprocess.SubprocessError) as exc:
            output, code = f"{type(exc).__name__}: {exc}", -1
        with _LOCK:
            _REPAIR.update(state="done" if code == 0 else "failed", code=code, output=output[-6000:])

    @router.post("/repair")
    async def repair() -> dict[str, Any]:
        member = _member()
        if not member.get("valid"):
            return {"ok": False, "error": "member_missing", "member": member}
        with _LOCK:
            start = _REPAIR["state"] != "running"
            if start:
                _REPAIR.update(state="running", code=None, output="")
        if start:
            threading.Thread(target=_run_repair, name="mordred-repair", daemon=True).start()
        return {"ok": True, "repair": _repair_view()}

    @router.get("/repair")
    async def repair_status() -> dict[str, Any]:
        return {"ok": True, "repair": _repair_view()}
