"""Keep Mordred in every Python environment Hermes's package manager builds.

Hermes (pm-managed installs, e.g. Hermes Desktop) rebuilds its dependency
environment on every update into a fresh directory. A package that was added
with ``uv pip install`` (what ``scripts/install.sh`` does) is not part of the
inputs of that rebuild, so after an update Mordred is simply gone.

The supported way in is a *directory plugin with a* ``pyproject.toml``: pm
makes every enabled plugin directory that declares Python requirements a uv
workspace member of each generation it builds (``pm/workspace.py``:
``enabled_member_dirs`` / ``_workspace_member``), and the plugin set is part of
the environment stamp, so a changed member also forces a re-sync
(``pm/packages.py``: ``expected_stamp``). ``mordred`` is already enabled and
already owns ``<home>/plugins/mordred/`` (the dashboard API shim), so this
module turns that folder into such a member.

Why the member *is* hermes-mordred instead of depending on it: Mordred's
metadata requires ``hermes-agent>=0.13.0``, while the workspace root is the
Hermes checkout itself, version ``0.0.0``. uv refuses that ("the name is
shadowed by one of your workspace members"). So the member is a buildable
project named ``hermes-mordred`` with Mordred's own requirements minus
``hermes-agent`` (exactly what the installer's ``--no-deps`` + own-requirements
step does) and a vendored copy of the installed ``mordred_hermes`` package.
pm seeds resolution from Hermes's existing lock and keeps Hermes's exact pins
binding, so this does not move Hermes's own packages.

The folder has no ``plugin.yaml``, so Hermes's agent-plugin scanner still sees
no directory plugin there that could shadow the ``mordred`` entry point.
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import sys
from collections.abc import Iterable
from dataclasses import dataclass
from importlib import metadata
from pathlib import Path
from typing import Any, NoReturn

_LOG = logging.getLogger(__name__)

DISTRIBUTION = "hermes-mordred"
PACKAGE = "mordred_hermes"
MARKER = "GENERATED by hermes-mordred"
# Extras that only matter for development or for optional integrations the
# user installs deliberately; never inferred from what happens to be present.
_NEVER_INFERRED = frozenset({"dev", "integration"})
_IGNORED_NAMES = frozenset({"__pycache__", ".DS_Store"})
_BOOTSTRAPS = ("mordred_hermes_config_decrypt.pth", "mordred_hermes_runtime.pth")
WINDOWS_REINSTALL_REMEDY = (
    "Automatic package-manager registration and repair are not supported on Windows. "
    "After a Hermes update, rerun the original Windows installer, keeping the existing Hermes home "
    "and custody keys, then restart Hermes."
)


def _platform() -> str:
    """Platform admission seam; never patch process-global ``sys.platform``."""
    return sys.platform


@dataclass(frozen=True)
class InstallSource:
    """Where the running Mordred came from, enough to rebuild it."""

    version: str
    kind: str  # "pypi" | "path"
    path: str | None
    editable: bool
    extras: tuple[str, ...]


def _canonical(name: str) -> str:
    return name.lower().replace("_", "-").replace(".", "-")


def _distribution() -> metadata.Distribution:
    return metadata.distribution(DISTRIBUTION)


def _direct_url(dist: metadata.Distribution) -> dict[str, Any] | None:
    text = dist.read_text("direct_url.json")
    if not text:
        return None
    try:
        data = json.loads(text)
    except ValueError:
        return None
    return data if isinstance(data, dict) else None


def _installed(name: str) -> bool:
    try:
        metadata.distribution(name)
    except metadata.PackageNotFoundError:
        return False
    return True


def _requirements(dist: metadata.Distribution) -> list[Any]:
    from packaging.requirements import Requirement

    return [Requirement(spec) for spec in dist.requires or ()]


def _extra_requirements(dist: metadata.Distribution, extra: str) -> list[Any]:
    return [req for req in _requirements(dist) if req.marker is not None and _marker_extra(req, extra)]


def _marker_extra(req: Any, extra: str) -> bool:
    """True when *req* belongs to *extra* (and applies on this machine)."""
    try:
        return bool(req.marker.evaluate({"extra": extra})) and not bool(req.marker.evaluate({"extra": ""}))
    except Exception:
        return False


def _expand(dist: metadata.Distribution, extras: Iterable[str]) -> set[str]:
    """Close *extras* over self-references such as ``macos -> hermes-mordred[keyvault]``."""
    pending, seen = list(extras), set()
    while pending:
        extra = pending.pop()
        if extra in seen:
            continue
        seen.add(extra)
        for req in _extra_requirements(dist, extra):
            if _canonical(req.name) == DISTRIBUTION:
                pending.extend(req.extras)
    return seen


def inferred_extras(dist: metadata.Distribution | None = None) -> tuple[str, ...]:
    """The extras whose every requirement is installed here: what was installed.

    The installer always adds the platform extra (``macos`` / ``keyvault``) and
    then whatever the user asked for; reading it back from the environment
    reproduces that without a second record that could drift.
    """
    dist = dist or _distribution()
    declared = [e for e in (dist.metadata.get_all("Provides-Extra") or []) if e not in _NEVER_INFERRED]
    chosen = []
    for extra in declared:
        reqs = [r for r in _extra_requirements(dist, extra) if _canonical(r.name) != DISTRIBUTION]
        if reqs and all(_installed(r.name) for r in reqs):
            chosen.append(extra)
    return tuple(sorted(chosen))


def install_source(dist: metadata.Distribution | None = None) -> InstallSource:
    dist = dist or _distribution()
    direct = _direct_url(dist)
    path: str | None = None
    editable = False
    kind = "pypi"
    if direct and str(direct.get("url", "")).startswith("file://"):
        kind = "path"
        from urllib.parse import unquote, urlparse

        path = unquote(urlparse(str(direct["url"])).path)
        editable = bool((direct.get("dir_info") or {}).get("editable"))
    return InstallSource(dist.version, kind, path, editable, inferred_extras(dist))


def built_from_member(source: InstallSource) -> bool:
    """Whether this install is pm's build of the member rather than a user install."""
    return source.kind == "path" and source.path is not None and "/plugin-sources/" in source.path.replace("\\", "/")


def member_requirements(dist: metadata.Distribution, extras: Iterable[str]) -> list[str]:
    """Mordred's own requirements for *extras*, without ``hermes-agent`` or markers.

    Markers are evaluated for this machine (the member is rebuilt here only);
    ``hermes-agent`` is the workspace root and must never come from an index.
    """
    wanted = _expand(dist, extras)
    out: list[str] = []
    for req in _requirements(dist):
        name = _canonical(req.name)
        if name in {DISTRIBUTION, "hermes-agent"}:
            continue
        if req.marker is not None:
            try:
                applies = any(bool(req.marker.evaluate({"extra": e})) for e in ("", *sorted(wanted)))
            except Exception:
                applies = False
            if not applies:
                continue
        if req.url:
            continue  # pm drops direct URLs anyway; never let one in.
        spec = f"{req.name}{'[' + ','.join(sorted(req.extras)) + ']' if req.extras else ''}{req.specifier}"
        if spec not in out:
            out.append(spec)
    return sorted(out, key=str.lower)


def _toml_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _toml_list(values: Iterable[str]) -> str:
    items = list(values)
    if not items:
        return "[]"
    return "[\n" + "".join(f"  {_toml_str(v)},\n" for v in items) + "]"


def render_pyproject(dist: metadata.Distribution, source: InstallSource) -> str:
    groups: dict[str, list[tuple[str, str]]] = {}
    for ep in dist.entry_points:
        groups.setdefault(ep.group, []).append((ep.name, ep.value))
    lines = [
        f"# {MARKER}. Do not edit: Mordred rewrites this file when it starts.",
        "# It makes Hermes's package manager (pm) rebuild Mordred into every new",
        "# dependency environment (Hermes updates, `hermes pm repair`). Delete this",
        "# folder (or run `hermes-mordred uninstall`) to stop that.",
        "",
        "[project]",
        f"name = {_toml_str(DISTRIBUTION)}",
        f"version = {_toml_str(source.version)}",
        f"requires-python = {_toml_str(dist.metadata['Requires-Python'] or '>=3.11')}",
        f"dependencies = {_toml_list(member_requirements(dist, source.extras))}",
    ]
    for group in sorted(groups):
        if group == "console_scripts":
            lines += ["", "[project.scripts]"]
        else:
            lines += ["", f"[project.entry-points.{_toml_str(group)}]"]
        lines += [f"{_toml_str(name)} = {_toml_str(value)}" for name, value in sorted(groups[group])]
    lines += [
        "",
        "[build-system]",
        'requires = ["hatchling>=1.18"]',
        'build-backend = "hatchling.build"',
        "",
        "[tool.hatch.build.targets.wheel]",
        f"packages = [{_toml_str(PACKAGE)}]",
        "",
        "[tool.hatch.build.targets.wheel.force-include]",
        *(f"{_toml_str(name)} = {_toml_str(name)}" for name in _BOOTSTRAPS),
        "",
        "[tool.hermes-mordred]",
        f"source = {_toml_str(source.kind)}",
        f"path = {_toml_str(source.path or '')}",
        f"editable = {'true' if source.editable else 'false'}",
        f"extras = {_toml_list(source.extras)}",
        "",
    ]
    return "\n".join(lines)


def _package_root() -> Path:
    import mordred_hermes

    return Path(mordred_hermes.__file__).resolve().parent


def _bootstrap_files(dist: metadata.Distribution, source: InstallSource, root: Path) -> dict[str, bytes]:
    """Read the canonical wheel-root hooks belonging to this package install.

    Editable wheels may contain stale copies of force-included files, so use
    the checkout recorded by PEP 610, bound to the running package directory.
    Wheel installs use only files owned by their distribution's RECORD.
    """
    if source.editable:
        checkout = Path(source.path) if source.path else None
        if checkout is None or (checkout / "src" / PACKAGE).resolve() != root.resolve():
            raise OSError("cannot locate startup bootstraps for this editable Mordred package")
        paths = {name: checkout / "packaging" / "pth" / name for name in _BOOTSTRAPS}
    else:
        if Path(str(dist.locate_file(PACKAGE))).resolve() != root.resolve():
            raise OSError("Mordred package and bootstrap distribution do not match")
        recorded = {str(path) for path in dist.files or ()}
        paths = {}
        for name in _BOOTSTRAPS:
            if name not in recorded:
                raise OSError(f"Mordred distribution is missing startup bootstrap {name}")
            paths[name] = Path(str(dist.locate_file(name)))
    files = {}
    for name, path in paths.items():
        if path.is_symlink() or not path.is_file():
            raise OSError(f"Mordred startup bootstrap is missing or unsafe: {path}")
        data = path.read_bytes()
        if not data.strip():
            raise OSError(f"Mordred startup bootstrap is empty: {path}")
        files[name] = data
    return files


def _tree(root: Path) -> dict[str, bytes]:
    files: dict[str, bytes] = {}
    for directory, dirs, names in os.walk(root):
        dirs[:] = sorted(d for d in dirs if d not in _IGNORED_NAMES and not d.endswith(".egg-info"))
        for name in sorted(names):
            if name in _IGNORED_NAMES or name.endswith((".pyc", ".pyo")):
                continue
            path = Path(directory) / name
            if path.is_symlink() or not path.is_file():
                continue
            files[path.relative_to(root).as_posix()] = path.read_bytes()
    return files


def pm_managed() -> bool:
    """Is the running Hermes one whose environments pm builds (Desktop / source installs)?"""
    import importlib.util

    try:
        return importlib.util.find_spec("pm.workspace") is not None
    except (ImportError, ValueError):
        return False


def ensure_member(
    plugin_dir: Path, *, package_root: Path | None = None, dist: metadata.Distribution | None = None
) -> bool:
    """Write or refresh the pm member in *plugin_dir*; return whether anything changed.

    Rewrites only on a real difference: every byte under the folder is part of
    pm's environment stamp, so a needless write would trigger a rebuild.
    """
    if _platform() == "win32":
        raise NotImplementedError(WINDOWS_REINSTALL_REMEDY)
    if plugin_dir.is_symlink() or plugin_dir.parent.is_symlink():
        return False
    # Every Hermes process (gateway, CLI, cron) registers the plugin; serialize the
    # rewrite. The lock lives outside the member folder, which pm hashes.
    lock_dir = plugin_dir.parent.parent / "mordred"
    lock_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
    from .._file_lock import private_flock

    def unsafe(path: Path) -> NoReturn:
        raise OSError(f"refusing unsafe lock file {path}")

    with private_flock(lock_dir / ".pm-member.lock", on_unsafe=unsafe, nonblock=False):
        return _ensure_member_locked(plugin_dir, package_root=package_root, dist=dist)


def _ensure_member_locked(plugin_dir: Path, *, package_root: Path | None, dist: metadata.Distribution | None) -> bool:
    dist = dist or _distribution()
    source = install_source(dist)
    root = package_root or _package_root()
    if root.resolve().is_relative_to(plugin_dir.resolve()) or built_from_member(source):
        # Running from the vendored copy itself, or from
        # pm's build of the member (its own copy under
        # environments/<id>/workspace/plugin-sources/). Its metadata no longer
        # says where Mordred came from or which extras were chosen, so
        # re-recording it would lose both and change the member — which makes
        # pm rebuild again on every start.
        return False
    # Validate every input before changing an existing member. A member without
    # these wheel-root hooks would silently lose the pre-import runtime guards.
    bootstraps = _bootstrap_files(dist, source, root)
    pyproject = render_pyproject(dist, source).encode()
    wanted = _tree(root)
    vendored = plugin_dir / PACKAGE
    current_tree = _tree(vendored) if vendored.is_dir() and not vendored.is_symlink() else None
    changed_files = {
        name: data
        for name, data in {**bootstraps, "pyproject.toml": pyproject}.items()
        if (plugin_dir / name).is_symlink()
        or not (plugin_dir / name).is_file()
        or (plugin_dir / name).read_bytes() != data
    }
    if current_tree == wanted and not changed_files:
        return False
    plugin_dir.mkdir(parents=True, exist_ok=True)
    if current_tree != wanted:
        staging = plugin_dir / f".{PACKAGE}.new"
        old = plugin_dir / f".{PACKAGE}.old"
        for leftover in (staging, old):
            if leftover.exists():
                shutil.rmtree(leftover)
        for rel, data in wanted.items():
            out = staging / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_bytes(data)
        if vendored.exists():
            vendored.rename(old)
        staging.rename(vendored)
        if old.exists():
            shutil.rmtree(old)
    for name, data in changed_files.items():
        tmp = plugin_dir / f".{name}.tmp"
        tmp.write_bytes(data)
        tmp.replace(plugin_dir / name)
    return True


def remove_member(plugin_dir: Path) -> bool:
    """Drop the member project, package and bootstraps; leave other files alone."""
    if _platform() == "win32":
        raise NotImplementedError(WINDOWS_REINSTALL_REMEDY)
    removed = False
    target = plugin_dir / "pyproject.toml"
    if target.is_file() and MARKER in target.read_text(encoding="utf-8", errors="replace"):
        target.unlink()
        removed = True
    vendored = plugin_dir / PACKAGE
    if vendored.is_dir() and not vendored.is_symlink():
        shutil.rmtree(vendored)
        removed = True
    for name in _BOOTSTRAPS:
        bootstrap = plugin_dir / name
        if bootstrap.is_file() or bootstrap.is_symlink():
            bootstrap.unlink()
            removed = True
    return removed


def member_status(plugin_dir: Path) -> dict[str, Any]:
    """What the member records, read without importing anything Mordred-specific."""
    if _platform() == "win32":
        # ``present`` is unknown: the unported reader must not inspect profile files.
        return {
            "supported": False,
            "present": None,
            "valid": False,
            "reason": "not-ported-on-windows",
            "remedy": WINDOWS_REINSTALL_REMEDY,
        }
    import tomllib

    target = plugin_dir / "pyproject.toml"
    if not target.is_file():
        return {"present": False}
    try:
        text = target.read_text(encoding="utf-8")
        data = tomllib.loads(text)
        includes = (
            data.get("tool", {})
            .get("hatch", {})
            .get("build", {})
            .get("targets", {})
            .get("wheel", {})
            .get("force-include", {})
        )
        bootstraps_valid = all(
            includes.get(name) == name
            and not (plugin_dir / name).is_symlink()
            and (plugin_dir / name).is_file()
            and (plugin_dir / name).read_bytes().strip()
            for name in _BOOTSTRAPS
        )
    except (OSError, ValueError):
        return {"present": True, "valid": False}
    project = data.get("project", {})
    recorded = data.get("tool", {}).get("hermes-mordred", {})
    return {
        "present": True,
        "valid": MARKER in text and (plugin_dir / PACKAGE).is_dir() and bootstraps_valid,
        "version": project.get("version"),
        "source": recorded.get("source"),
        "path": recorded.get("path") or None,
        "extras": list(recorded.get("extras") or []),
    }


def environment_info() -> dict[str, Any]:
    """The interpreter/environment this process runs in (for the status line)."""
    prefix = Path(sys.prefix)
    env_id = prefix.parent.name if prefix.name == "venv" else prefix.name
    return {"prefix": str(prefix), "environment": env_id, "python": sys.version.split()[0], "platform": _platform()}
