#!/usr/bin/env bash
# Install mordred-hermes into the Python environment owned by Hermes Agent.
#
# This intentionally follows Hermes's own install layout instead of creating a
# second virtual environment. It installs code only: configuration, key
# creation, and encryption remain explicit follow-up steps.

set -euo pipefail

readonly HERMES_INSTALL_URL="https://hermes-agent.nousresearch.com/install.sh"
readonly HERMES_INSTALL_COMMAND="curl -fsSL ${HERMES_INSTALL_URL} | bash"
# Keep in sync with `[tool.mordred] min-hermes-version` in pyproject.toml;
# tests/test_user_installer.py asserts the two agree.
readonly MIN_HERMES_VERSION="0.13.0"
readonly LAUNCHER_MARKER='# Generated by the mordred-hermes installer.'

info() {
  printf 'mordred: %s\n' "$*"
}

warn() {
  printf 'mordred: warning: %s\n' "$*" >&2
}

fail() {
  printf 'mordred: error: %s\n' "$*" >&2
  exit 1
}

# Match the isolation used by Hermes's installer. A caller's Python or uv
# project settings must not redirect package discovery into another checkout,
# an ambient override must not redirect the download away from PyPI, and none
# of it may weaken how the download is verified. UV_NO_CONFIG only silences
# config *files*, so each variable has to be cleared by name.
unset PYTHONHOME PYTHONPATH UV_PYTHON UV_PROJECT_ENVIRONMENT
# Where packages come from.
unset UV_INDEX UV_INDEX_URL UV_DEFAULT_INDEX UV_EXTRA_INDEX_URL UV_FIND_LINKS
unset UV_INDEX_STRATEGY UV_NO_SOURCES UV_OFFLINE UV_CONFIG_FILE
# Whether they are verified, and which ones are eligible.
unset UV_INSECURE_HOST UV_NO_VERIFY_HASHES UV_SYSTEM_CERTS
unset UV_PRERELEASE UV_EXCLUDE_NEWER
# Where they land: the venv is chosen by --python, never by ambient state.
unset UV_SYSTEM_PYTHON UV_BREAK_SYSTEM_PACKAGES
export UV_NO_CONFIG=1

find_hermes_command() {
  command -v hermes 2>/dev/null || true
}

launcher_first_line() {
  local launcher="$1" first_line
  first_line="$(head -n 1 "$launcher" 2>/dev/null || true)"
  printf '%s\n' "${first_line%$'\r'}"
}

looks_like_python() {
  local candidate="$1"
  [[ "${candidate##*/}" == python* ]] && [[ -x "$candidate" ]]
}

path_is_shell_safe() {
  # The generated launcher embeds this path inside a double-quoted `exec`. A
  # quote, backslash, backtick, `$` or newline would break out of that quoting
  # and turn the launcher into an injection point on every later invocation.
  case "$1" in
    *[\"\\\`\$]* | *$'\n'*) return 1 ;;
  esac
  return 0
}

python_from_shebang() {
  local launcher="$1"
  local first_line

  first_line="$(launcher_first_line "$launcher")"
  case "$first_line" in
    '#!'/*)
      first_line="${first_line#\#!}"
      # A console-script shebang contains one absolute interpreter path. Do not
      # guess when a wrapper adds flags or uses /usr/bin/env.
      if [[ "$first_line" != *[[:space:]]* ]] && looks_like_python "$first_line"; then
        printf '%s\n' "$first_line"
      fi
      ;;
  esac
}

python_from_exec_line() {
  # Hermes's own launcher is a bash wrapper, so its shebang only names bash:
  #
  #   #!/usr/bin/env bash
  #   unset PYTHONPATH
  #   unset PYTHONHOME
  #   exec "<venv>/bin/python" "<install>/hermes" "$@"
  #
  # The interpreter has to come from the exec line instead. Without this the
  # shebang probe never matches a real Hermes install and detection silently
  # falls through to the canonical directory.
  local launcher="$1"
  local line candidate

  case "$(launcher_first_line "$launcher")" in
    '#!'*) ;;
    *) return ;;
  esac

  while IFS= read -r line; do
    line="${line%$'\r'}"
    if [[ "$line" =~ ^[[:space:]]*exec[[:space:]]+\"(/[^\"]+)\" ]]; then
      candidate="${BASH_REMATCH[1]}"
      if looks_like_python "$candidate"; then
        printf '%s\n' "$candidate"
      fi
      return
    fi
  done < <(head -n 40 "$launcher" 2>/dev/null)
}

find_hermes_python() {
  # Prefer the environment behind the `hermes` the caller actually runs. The
  # canonical directory is only a fallback: when a second Hermes install shadows
  # it on PATH, installing into the canonical one would leave `hermes` and
  # `hermes-mordred` pointing at different environments.
  local launcher="$1"
  local hermes_home candidate detected

  if [[ -n "$launcher" ]]; then
    detected="$(python_from_shebang "$launcher")"
    if [[ -z "$detected" ]]; then
      detected="$(python_from_exec_line "$launcher")"
    fi
    if [[ -n "$detected" ]]; then
      printf '%s\n' "$detected"
      return
    fi
  fi

  # `${HOME}` bare would abort with `HOME: unbound variable` under `set -u`
  # instead of reaching the "install Hermes first" guidance below.
  hermes_home="${HERMES_HOME:-${HOME:-}/.hermes}"
  for candidate in \
    "${hermes_home}/hermes-agent/venv/bin/python3" \
    "${hermes_home}/hermes-agent/venv/bin/python"; do
    if [[ -x "$candidate" ]]; then
      printf '%s\n' "$candidate"
      return
    fi
  done
}

python_environment_root() {
  # Only install into an environment Mordred may own: a virtualenv, or a conda
  # environment for the rare hand-built Hermes install. Anything else is a
  # system or shared interpreter where `uv pip install` either refuses outright
  # or scatters console scripts outside the interpreter's own bin/.
  local python_path="$1" root
  root="$(cd "$(dirname "$python_path")/.." 2>/dev/null && pwd)" || return 1
  if [[ -f "${root}/pyvenv.cfg" || -d "${root}/conda-meta" ]]; then
    printf '%s\n' "$root"
    return 0
  fi
  return 1
}

version_at_least() {
  # Compare the major.minor ordinals only: the gate has never been patch-level,
  # and a trailing pre-release segment must not affect it. `10#` forces base 10
  # so a zero-padded segment is not read as octal.
  local have="$1" want="$2"
  local have_major have_minor want_major want_minor

  if [[ ! "$have" =~ ^([0-9]+)\.([0-9]+) ]]; then
    return 1
  fi
  have_major=$((10#${BASH_REMATCH[1]}))
  have_minor=$((10#${BASH_REMATCH[2]}))

  if [[ ! "$want" =~ ^([0-9]+)\.([0-9]+) ]]; then
    return 1
  fi
  want_major=$((10#${BASH_REMATCH[1]}))
  want_minor=$((10#${BASH_REMATCH[2]}))

  ((have_major > want_major || (have_major == want_major && have_minor >= want_minor)))
}

deps_are_consistent() {
  local uv_bin="$1" hermes_python="$2"
  "$uv_bin" pip check --python "$hermes_python" >/dev/null 2>&1
}

is_installer_launcher() {
  local path="$1"
  [[ -f "$path" ]] && head -n 5 "$path" 2>/dev/null | grep -qF "$LAUNCHER_MARKER"
}

write_launcher_file() {
  local target="$1" installed_cli="$2"
  cat >"$target" <<EOF && chmod 755 "$target"
#!/usr/bin/env bash
${LAUNCHER_MARKER} Safe to delete.
# Mirrors Hermes's own launcher: an ambient PYTHONPATH/PYTHONHOME must not
# redirect package discovery into a different checkout.
unset PYTHONPATH
unset PYTHONHOME
exec "${installed_cli}" "\$@"
EOF
}

install_launcher() {
  # Write a wrapper rather than a symlink. Hermes's own launcher unsets
  # PYTHONPATH/PYTHONHOME before exec; a bare symlink to the console script
  # would not, so an ambient PYTHONPATH could make `hermes-mordred` import a
  # different mordred_hermes than the one `hermes` loads. Owning the file also
  # means re-runs replace only launchers this installer wrote.
  local installed_cli="$1" hermes_launcher="$2"
  local link_dir link_path tmp

  if [[ -n "$hermes_launcher" ]]; then
    link_dir="$(dirname "$hermes_launcher")"
  else
    link_dir="${HOME}/.local/bin"
  fi
  link_path="${link_dir}/hermes-mordred"

  # A development checkout keeps `hermes` in the same venv bin/ that just
  # received the console script; there is nothing to wrap.
  if [[ "$link_path" -ef "$installed_cli" ]]; then
    printf '%s\n' "$installed_cli"
    return
  fi

  if { [[ -e "$link_path" ]] || [[ -L "$link_path" ]]; } && ! is_installer_launcher "$link_path"; then
    warn "not replacing ${link_path}; this installer did not create it"
    printf '%s\n' "$installed_cli"
    return
  fi

  if ! path_is_shell_safe "$installed_cli"; then
    warn "not generating a launcher: ${installed_cli} contains shell metacharacters"
    printf '%s\n' "$installed_cli"
    return
  fi

  # Every write below is checked explicitly. `set -e` does NOT apply here:
  # this function runs inside a command substitution, where errexit is
  # suppressed for the whole dynamic extent, so an unchecked failure would
  # run on to `mv` with an empty $tmp and bury the fact that the package
  # itself installed cleanly.
  if ! mkdir -p "$link_dir" 2>/dev/null ||
    ! tmp="$(mktemp "${link_dir}/.hermes-mordred.XXXXXX" 2>/dev/null)"; then
    warn "could not write to ${link_dir}; run ${installed_cli} directly"
    printf '%s\n' "$installed_cli"
    return
  fi

  if ! write_launcher_file "$tmp" "$installed_cli" || ! mv -f "$tmp" "$link_path"; then
    rm -f "$tmp"
    warn "could not write the launcher at ${link_path}; run ${installed_cli} directly"
    printf '%s\n' "$installed_cli"
    return
  fi
  printf '%s\n' "$link_path"
}

main() {
  local hermes_launcher hermes_python env_root uv_bin metadata hermes_version
  local platform package_spec installed_cli exposed_cli exposed_dir
  local deps_were_consistent=0

  hermes_launcher="$(find_hermes_command)"
  hermes_python="$(find_hermes_python "$hermes_launcher")"
  if [[ -z "$hermes_python" ]]; then
    printf 'Install Hermes Agent first with its official installer:\n  %s\n' "$HERMES_INSTALL_COMMAND" >&2
    fail "could not find a Hermes-managed Python environment"
  fi

  if ! env_root="$(python_environment_root "$hermes_python")"; then
    printf 'Mordred installs into Hermes'"'"'s own environment and will not modify a\n' >&2
    printf 'system or shared interpreter.\n' >&2
    fail "the detected Hermes interpreter is not in a virtual environment: ${hermes_python}"
  fi

  uv_bin="$(command -v uv 2>/dev/null || true)"
  if [[ -z "$uv_bin" ]]; then
    fail "uv is not on PATH; reload the shell after installing Hermes, then retry"
  fi

  if ! metadata="$("$uv_bin" pip show --python "$hermes_python" --no-python-downloads hermes-agent 2>/dev/null)"; then
    fail "the detected environment does not contain hermes-agent: ${env_root}"
  fi
  hermes_version="$(printf '%s\n' "$metadata" | awk -F ': ' '$1 == "Version" { print $2; exit }')"
  if [[ -z "$hermes_version" ]]; then
    fail "could not determine the installed Hermes Agent version"
  fi
  if ! version_at_least "$hermes_version" "$MIN_HERMES_VERSION"; then
    printf 'Update Hermes Agent, then run this installer again:\n  hermes update\n' >&2
    fail "Hermes Agent ${hermes_version} is older than the required ${MIN_HERMES_VERSION}"
  fi

  platform="$(uname -s)"
  case "$platform" in
    Darwin)
      package_spec='mordred-hermes[macos]'
      ;;
    Linux)
      package_spec='mordred-hermes[keyvault]'
      ;;
    *)
      fail "unsupported platform ${platform}; Mordred currently supports macOS and Linux"
      ;;
  esac

  # Mordred shares an environment with the running agent, so it can move a
  # dependency Hermes also pins. Record the state beforehand to report only a
  # conflict this install actually introduced.
  if deps_are_consistent "$uv_bin" "$hermes_python"; then
    deps_were_consistent=1
  fi

  info "Hermes Agent ${hermes_version} at ${hermes_python}"
  info "installing ${package_spec} from PyPI"
  "$uv_bin" pip install \
    --python "$hermes_python" \
    --no-python-downloads \
    --upgrade-package mordred-hermes \
    "$package_spec"

  if ((deps_were_consistent)) && ! deps_are_consistent "$uv_bin" "$hermes_python"; then
    warn "installing Mordred left conflicting dependencies in Hermes's environment"
    warn "inspect with: uv pip check --python ${hermes_python}"
  fi

  installed_cli="$(dirname "$hermes_python")/hermes-mordred"
  if [[ ! -x "$installed_cli" ]]; then
    fail "installation completed but ${installed_cli} was not created"
  fi
  exposed_cli="$(install_launcher "$installed_cli" "$hermes_launcher")"

  printf '\nMordred is installed. Configuration and keys were not changed.\n'
  printf 'Next, start the interactive setup:\n  %s configure\n' "$exposed_cli"
  exposed_dir="$(dirname "$exposed_cli")"
  case ":${PATH}:" in
    *":${exposed_dir}:"*) ;;
    *)
      printf '\nAdd %s to PATH to run the command by name.\n' "$exposed_dir"
      ;;
  esac
}

main "$@"
